### ISSUE TITLE
Can't skip over binding a controller button if no buttons are bound yet

### ISSUE THREAD

**Issue by Hew-ux** [batocera-linux/batocera-emulationstation#1103]
Meaning if your controller doesn't have D-pad Up (the first button in the list), you cannot bind the rest of your controller.

**Comment by fabricecaruso** [comment]
If the controller does not have d-pad, then bind up to the analog up, then ignore the analog settings ? No ?

**Comment by Hew-ux** [comment]
Issue with doing that: some controllers, like all Retrobit controllers, will act as if though you are continually holding up + left due to the dpad being treated as an analog stick. Rion on the discord is the one who told me about this, ask him for further information.

**Comment by fabricecaruso** [comment]
It should not be a problem : analog sticks are well supported when assigned to dpad entries.
Anyway, I don't have such a device... So I can't reproduice, & I don't see what to do

**Comment by Redemp** [comment]
The issue here is that it is impossible to skip setting up a D-PAD.
For all other inputs you can keep holding a button to skip over it. 

So what I first did was using up 4 of my button inputs for the D-PAD. :unamused: 
Then setup my Left Analog Joystick with my D-PAD
Saved the setting, copied the setting from es_input.cfg

`<input name="joystick1left" type="axis" id="0" value="-1" code="0" />`
`<input name="joystick1up" type="axis" id="1" value="-1" code="1" />`
`<input name="joystick2left" type="axis" id="3" value="-1" code="3" />`
`<input name="joystick2up" type="axis" id="4" value="-1" code="4" />`

Redid the controller configuration again but this time I setup the D-PAD.

This resulted in these setting
`<input name="down" type="axis" id="1" value="1" code="1" />`
`<input name="left" type="axis" id="0" value="-1" code="0" />`
`<input name="right" type="axis" id="0" value="1" code="0" />`
`<input name="up" type="axis" id="1" value="-1" code="1" />`

Now I had to edit es_input.cfg and delete those values and replaced the with the analog values. 
All because you can skip setting up a Digital D-PAD.

**Comment by Redemp** [comment]
Any news on this issue? 
Would really like to have the option to skip setting up a digital d-pad.
This issue is not only for Retro-Bit controllers but also for arcade encoders like the JammaASD for example.

**Comment by fabricecaruso** [comment]
button binding order has changed on the v33 configuration screen. It should be enough as the first elements you define are A & B buttons. Can you test with v33 ?

**Comment by DerangedPineapple** [comment]
I concur that skipping any arbitrary button mapping is useful and one might even say crucial in some situations where Batocera is used to play only C64, Atari St and Amiga500 games via mouse, keyboard and original DE-9/DB-9 joysticks connected via JAKADAPTER (Stelladapter compatible).

Currently previously mentioned setup is not possible at all as old school joysticks has only one button. Mapping joysticks currently in a way that user wants to launch games with joystick's button press is impossible now as button A mapping cannot be skipped.

My use case would be as follows:
Configure keyboard and 1 or 2 DE-9 joysticks connected via JAKADAPTER, then use joysticks to move around in ES and launch games bu selecting desired game and pressing button. Everything else in ES could be accessed via keyboard.

I don't really see the point forcing non skippable buttons in the first place as it hinders the possibilities how Batocera could be used..

**Comment by Hew-ux** [comment]
Allow me to demonstrate. Here is the controller configuration screen after I have configured a "controller" (in this case, my keyboard) and then scrolled up instead of pressing "OK":
![screenshot-2022 03 09-21h08 14](https://user-images.githubusercontent.com/67527064/157420004-8554359f-ad37-41fc-8eeb-3897fac750b6.png)
Notice the tip which says "HOLD ANY BUTTON TO SKIP" near the top of the window.
Now if I were to move the cursor up one button to the first mappable button, A:
![screenshot-2022 03 09-21h09 45](https://user-images.githubusercontent.com/67527064/157420245-164137ed-9c1b-492c-81e0-742129ffd5a1.png)
The tooltip offering to skip the mapping is now gone! To me, this seems like an artificial limitation. This limitation is what we are requesting be removed; considering that you have to hold down a button anyway to even start the configuration (and this is done before _any_ buttons are assigned) it seems like a rather unnecessary thing to limit in the first place.

**Comment by dogg2k1** [comment]
Hi,  I am experiencing the same issue now with v37.  Has anyone figured this out?  I was on v32 prior to this and it was not a problem to skip over the D-Pad buttons.  I am mapping an arcade control panel and do not have a D-Pad...

Any help is appreciated!

**Comment by Redemp** [comment]
Any news on this? We still can't skip button/axis binding in 2023??

**Comment by dogg2k1** [comment]
I've heard nothing.  I think it is a shame that we are stuck using v32 because of this!  Hopefully this can be included in v38

**Comment by fabricecaruso** [comment]
This should solve the case.
https://github.com/batocera-linux/batocera-emulationstation/pull/1568
