### ISSUE TITLE
Using scripts to launch a background service renders blank error logs

### ISSUE THREAD

**Issue by Hew-ux** [batocera-linux/batocera-emulationstation#1150]
**Issue:** The log files in `/userdata/system/logs` are empty when using ES scripts to run a background service.

**Expected behaviour:** For the logs to still function when using custom scripts.

**Logs:** Self-explanatory why they are not present here.

**Additional info:** One example is if you were to download and run the Pixelcade software: https://pixelcade.org/batocera/ but I'm also sure this would be applying to any scripts that launch a background service to be run continually.

**Comment by fabricecaruso** [comment]
Absolutely not related to ES in ny way.
No logs in /userdata/system/logs is related to EmulationStation.
These are batocera & configgen logs.

**Comment by Hew-ux** [comment]
This is related to ES. It only occurs when using custom ES scripts, not when using Batocera custom scripts. Please try the reproduction method and you will see.

Sorry for not specifying that from the start.

**Comment by fabricecaruso** [comment]
What do you scripts do ?

**Comment by Hew-ux** [comment]
Launches a curl request to a Java webservice.

I've found that if the curl command is replaced with one with the verbose tag, then the curl output becomes visible in the logs. So it seems like ES is using the output of its custom scripts as the last thing to be written to stderr and stdout.

**Comment by fabricecaruso** [comment]
mmm you're right, on linux the following code is used : https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/platform.cpp#L129 ( I didn't remember that, this code was probably written before by someone else before )
As the scripts output are redirected to the log files (  "2>[..]" ), you can't redirect youself. I suppose you do that ( but I didn't see any script code... ).
Instead you have to output what you do to the console. 
So in your scripts, you have to verbose your output instead of redirecting them.

**Comment by Hew-ux** [comment]
That's what I said I did, not sure what difference that would make.
Incidentally I did try redirecting the script's output to a different tty, but that just resulted in the logs becoming blank again. The issue fundamentally seems to be with the way that the order of the output of the user's custom scripts are recorded.
If we could find the piece of code responsible, I imagine it would be as simple as changing ">" to ">>" or something similar.
