### ISSUE TITLE
(Feature Request) Enhancements to scraper

### ISSUE THREAD

**Issue by PIC16f841** [batocera-linux/batocera-emulationstation#1271]
Hi,
It would be nice if the scraper would be able to de-dup assets that are identical. For example if I have 5 different versions of the same rom with the same screenshot/wheel/video, they all should point to the same unique file on disk instead of storing 5 duplicates of the same file. This is particularly important for videos where a lot of space on disk can be saved this way. We are already storing CRC and MD5 for roms in the gamelist (I guess for retroachievements and netplay) so it could be implemented adding new hash entries for resources that are scraped and can be repeated (screenshot, video, etc) either in the gamelist file or somewhere else if you want to avoid cluttering the gamelist with extra assets metadata.

Right now, the scraper assumes it should scrape the info on the language set in emulationstation. Another cool feature that makes a difference is to add a combo to select the language used by the scraper or even better a list of language priorities to use.

**Comment by PIC16f841** [comment]
Also implementation for the special case of fbneo and mame where we have 2 folders of different roms pointing to the same DB, it should either crosscheck hashes from both folders (and store just one copy of the asset on either of the folders only) or unify both systems assets under the same folder. This same logic can be extended as far as you want to the point of storing all game assets under the same folder, as there can be "corner" cases where the assets are the same for games published on different systems (for example, versions of 8-16 bits games published for modern virtual consoles) but I guess the sweet spot is to find a way to "share" assets somehow between both "arcade folders" at least

**Comment by nadenislamarre** [comment]
instead of doing something complicated in es
-- moreover, links are not possible on some systems like fat,
i guess that you should go to btrfs file system, while some tools like dedup are aleady available. it is transparent, and it deduplicate any file on the disk.

https://wiki.gentoo.org/wiki/Duperemove

**Comment by Fishaphrodite** [comment]
It appears ES can actually handle images and such being outside of the rom folder altogether, it also can use the same image for multiple games (it's all a matter of pointing to it in the .xml; this would also work with systems unable to use symlinks and hardlinks)

I guess the "goal" would be to be available to verify the media files being referenced into the several xmls and keep only one as being the reference? I'm not sure this would fit an automatic use, but it does feel related to what the "clean gamelists and unused medias" could do in a way (I don't know how ES handles this however, so I may be wrong).

(as for arcade, I wonder if you couldn't just manually copy the xml from one system fully scrapped to the other, then edit the image path in bulk to reference the media folder in an absolute way instead of a relative way, as the romnames are fixed).

**Comment by PIC16f841** [comment]
Another idea that I mentioned briefly on discord, pasting it here so it won't be lost.

I've noticed some scrape providers (like arcadeitalia) has short videos links to youtube. Could emulationstation be able to play videos from a YouTube URL so we would avoid storing them locally? If this hasn't been implemented then I suppose is cause it could be against YouTube terms and conditions but I'm not sure of that, emulationstation could even upload the videos from screenscrapper to our own personal YouTube/vimeo/etc accounts for "personal use" and play them from there ....

**Comment by PIC16f841** [comment]
> instead of doing something complicated in es -- moreover, links are not possible on some systems like fat, i guess that you should go to btrfs file system, while some tools like dedup are aleady available. it is transparent, and it deduplicate any file on the disk.
> 
> https://wiki.gentoo.org/wiki/Duperemove

Could we include this or any other dedup tool as part of batocera then? A new menu entry "dedup roms and scraped resources" available only if userdata partition is btrfs?
Block dedup could even work for roms that are "clones/hacks" or from different regions, i.e they are 99% binary similar, not sure if the fragmentation would be to much but at the very least whole files dedup makes a lot of sense for scraped resources

**Comment by fabricecaruso** [comment]
No sorry. The scraper is meant to be simple. 
We're not going to compare every medias to make sure they are the same & reference them from another system's folder.
If you really want this kind of thing, create your own external tool ( & share with the community )
