### ISSUE TITLE
No scrape function for Videopac+ G7400

### ISSUE THREAD

**Issue by zognic** [batocera-linux/batocera-emulationstation#1420]
Since we splitted Magnavox Odysse2 & Phillips Videopac+ we cannot scrape anymore the Videopac+

`{ "videopac",				VIDEOPAC_ODYSSEY2 },`
need to be changed to

`{ "videopacplus",				VIDEOPAC_ODYSSEY2 },`

**Comment by fabricecaruso** [comment]
"Need to be changed" -> Added maybe, not changed.

That happens because platform is not set in the system declaration
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_systems.yml#L1671

I would be better to add this line to the system declaration, as platform tag is used for scrapping :
platform:   videopac

**Comment by zognic** [comment]
Than we will change on es_system side, `videopacplus` will be renamed to `videopac`
