### ISSUE TITLE
Bug in v37 Steam Deck: R4 mouse-click breaks controller mapping

### ISSUE THREAD

**Issue by dfilskov** [batocera-linux/batocera-emulationstation#1474]
Please watch video.

On Steam Deck when you try to map Right stick press in CONTROLLER MAPPING to R4 the mapping jumps back and replaces the analogue stick mapping.

**Comment by dfilskov** [comment]
Uploading Mapping_R4_is_broken.mp4…

**Comment by dfilskov** [comment]
https://github.com/batocera-linux/batocera-emulationstation/assets/15096058/e4f67722-18a5-4e52-bf1a-eaa453f14d65

**Comment by joinski1** [comment]
@dfilskov which button on Steam Deck is R4?

**Comment by dfilskov** [comment]
Upmost rear button for the right middle finger:

https://www.androidheadlines.com/wp-content/uploads/2022/04/Steam-Deck-Rear-Buttons-1420x799.jpg

**Comment by joinski1** [comment]
Okay, my guess is, that it is because since v37 the R4 and R5 buttons on Steam Deck are preconfigured in ES now and acting as right and left mouse-click in the F1 File Manager (which can be accessed since v37 with a press on the button with the three dots below the right trackpad).
So you should better use Left and Right stick press as Left and Right stick press ;) (the analog sticks of the steam deck can be pressed and therefore used as buttons, if you did not know this yet).
Otherwise you would have to map those buttons within RetroArch options or via editing the config-files of the standalone emulators yourself. See wiki on how to edit button mapping per system/emulator.

**Comment by dfilskov** [comment]
prrssed: I know but it's horrible :) using a joystick for emulating touch input on e.g. an NDS touchscreen isn't easy - but press'n'holding down on the stick makes it impossible to use - pressing prevents precise movment. That's why L4 and R4 is perfect as stick press. And assigning them to stick presses makes them available for mapping in RetroArch.

**Comment by dfilskov** [comment]
The issue was also present in v36.

**Comment by joinski1** [comment]
@dfilskov 
No in v36 the issue was not present, you could assign R4 and R5 to every button you want (i just tested it on my Steam Deck with v36).

Regarding NDS touch control:
libretro/desmume r2 is touchpanel press
libretro/melonds r2 is switching position of displays, here you have to press R3 (analog joystick press) and yes, i agree, this feels a bit awkward
melonds standalone touchscreen of steam deck does work

so best is to use melonds standalone or libretro/desmume, or if you absolutely wish to use libretro/melonds, there should be the possibility to change the assignment of R2 in the RetroArch Settings (from display position switching to touch panel press)

**Comment by dfilskov** [comment]
Got it! - thanks - yeah, I can use some workarounds.

Hope at some point it can be made to work correctly again, though - like in v36.

**Comment by joinski1** [comment]
Why do you prefer using R4 or R5 instead of R2 or a real touchscreen press?

**Comment by dfilskov** [comment]
I can use other buttons too, that's OK (sometimes R2 is nice for other actuons, though) - I just see it as a bug that you can't assign all the Steam deck's keys in ES - or at least a bug that keys you cannot assign in ES do something "unfriendly" and unpredictable with no warning (as in the video) if you try :)

**Comment by dfilskov** [comment]
perhaps it's possible for the user to disable mouse buttons in ES.

I can't make F1 appear - the ••• button doesn't react. Not sure if I have disabled it in the conf, though. I've disabled a lot of buttons in RA but I don't think that should affect ES.

**Comment by dfilskov** [comment]
Ah yes. The ••• works like the F1 key did in ES when you're not viewing game lists. That's good.

And R4 and R5 works too as mouse buttons in the file manager.

Perhaps those mappings could be made to only work in the file manager and not in the ES menus/games.

**Comment by dfilskov** [comment]
It seems the mouse pointer is present - but invisible - in ES now - and always centeret and happens to hover over the CONTROLLER MAPPING Left analogue stick Left mapping which is causes the unfortinate reaction.

**Comment by dfilskov** [comment]
Workaround found:

In Main Menu / CONTROLLER & BLUETOOTH SETTINGS / STEAMDECK MOUSE/GUN SETTINGS set MODE to GUN while mapping R4 in CONTROLLER MAPPING. That will prevent R4 from working as a mouse-click inside ES menus.

**Comment by dfilskov** [comment]
> Why do you prefer using R4 or R5 instead of R2 or a real touchscreen press?

Is there a way to make touchscreen taps work in RetroArch?

**Comment by fabricecaruso** [comment]
I'm closing this one as this issue is not directly related to EmulationStation but what the systems ( batocera ) sends to SDL when clicking.
We won't be able to change anything on EmulationStation's side.
