### ISSUE TITLE
Game description in Chinese display issues.

### ISSUE THREAD

**Issue by htf6782414** [batocera-linux/batocera-emulationstation#254]
In any ES theme ( like es-theme-Simple ) used the Detailed gamelist view style ,it will display the game  descriptions which typed in <desc> part of the gamelist.xml.

The descriptions in English or another EUR languages, It will display rightly.  It will automatically line feed and automatically scroll, but the descriptions in Chinese does not.(The Chinese descriptions is not download with the SCRAPER , I translated it and type it in.  ) 

The descriptions in Chinese Can't line feed automatically, If the descriptions text is too long in a line , the overflow part will disappear, I can't see it.

So , is anybody knows how to fix it?

**Comment by asakous** [comment]
this version has some solutions  https://github.com/eagle0wl/EmulationStation/commit/43150fc920ec56afa81ea29abfe31608be092d65

**Comment by yingw** [comment]
@htf6782414  I guess it's because the default textview in cpp will not correctlly warp double byte language. My temporary solution is to add a space between these double byte characters and single bytes. I use notepad++ replacement function with regular exp to replace "([A-Z])([^\x00-\xff])" to "\1 \2", this help a little but not prefect. Then checked eagle0wl 's patch and guest that will work.

**Comment by fabricecaruso** [comment]
Probably obsolete
