### ISSUE TITLE
Shaders from ES vs shaders from retroarch

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#438]
It seems to that there is a sort of non-coherency between ES and retroarch. E.g. when you set up ZFAST shader in ES you can turn it off with L1/L2 + hotkey without return -- to get it back you have to save a state, exit and run the game again. I think that the best solution is to set up in ES retroarch configuration in a way to disable switching shaders through retroarch.

**Comment by Darknior** [comment]
It's what i do myself, i remove this bad feature that my children use by error and make problems :(
But Batocera waht to let the user choose what it want to do himself ...
For my part remove these keys is better for users, to change shader using LR menu is the best solution.

You can write it in batocera.conf

> ## GAMEPAD ##
# Disable Savastate slot change key
global.retroarch.input_state_slot_decrease_btn=nul
global.retroarch.input_state_slot_increase_btn=nul
# Disable Shader change key
global.retroarch.input_shader_prev_btn=nul
global.retroarch.input_shader_next_btn=nul

**Comment by mistepien** [comment]
Thank you very much!
In my case shader buttons were attached to axis or sth. It works for me:

#Disable Shader change key
global.retroarch.input_shader_next = "nul"
global.retroarch.input_shader_next_axis = "nul"
global.retroarch.input_shader_next_btn = "nul"
global.retroarch.input_shader_next_mbtn = "nul"
global.retroarch.input_shader_prev = "nul"
global.retroarch.input_shader_prev_axis = "nul"
global.retroarch.input_shader_prev_btn = "nul"
global.retroarch.input_shader_prev_mbtn = "nul"

It would great thing to have a switch in ES menu putting that into batocera.conf file.

**Comment by mistepien** [comment]
But this is enough:

global.retroarch.input_shader_next_axis = "nul"
global.retroarch.input_shader_next_btn = "nul"
global.retroarch.input_shader_next_mbtn = "nul"
global.retroarch.input_shader_prev_axis = "nul"
global.retroarch.input_shader_prev_btn = "nul"
global.retroarch.input_shader_prev_mbtn = "nul"

with that switching shaders witn "m" and "n" keys (keyboard) is kept

**Comment by Darknior** [comment]
Yes for sure, strange you have to configure AXIS .... maybe it's for your game controller ?
On mine button is enough ... 

`## GAMEPAD ##
# Disable Savastate change slot on gampad
global.retroarch.input_state_slot_decrease_btn=nul
global.retroarch.input_state_slot_increase_btn=nul
# Disable Shader change on gamepad
#global.retroarch.input_shader_next=nul
global.retroarch.input_shader_next_axis=nul
global.retroarch.input_shader_next_btn=nul
global.retroarch.input_shader_next_mbtn=nul
#global.retroarch.input_shader_prev=nul
global.retroarch.input_shader_prev_axis=nul
global.retroarch.input_shader_prev_btn=nul
global.retroarch.input_shader_prev_mbtn=nul
`

Because if i use SPACE like you it doesn't work fine.
Cool if it help you :)

I'm not sure @nadenislamarre is ok to add some settings like these to Batocera ... or a switch menu ... but for sure make possible to activate or not them from ES can help users.

Or to remove these settings  from the gamepad settings.

**Comment by mistepien** [comment]
I have 8bitdo SN30 PRO USB (wired).

**Comment by mistepien** [comment]
In BT version you have 4 modes, while in wired version you have just one. IMHO this is the difference.

**Comment by fabricecaruso** [comment]
Not related to ES. Probably obsolete
