### ISSUE TITLE
heart for favorites in es_carbon

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#477]
Yesterday I made git clone and build the whole system. As in detailed gamelist view in es_carbon, near below video I see [heart] in case of games with favourite tag.

**Comment by fabricecaruso** [comment]
Because the theme you use had md_favorite defined, which is a flag that was created once years ago in a ES retropie alternate fork. Some old themes were adapted for this fork. But no one removed it or fixed it as it did not show.
Simply update the theme to the latest version on my git ( if it's carbon ). Or remove "md_favorite" element in the theme.
Note : this is also true for md_kidgame & md_hidden.
