### ISSUE TITLE
Disabling L2 for pcengine

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#589]
If my kid presses L2 in pcengine emulation than we got this notice "6-button mode selected" and until L2 is pressed again playing is not possible. It would be great to have some switch in ES to disable that uniq "feature".

**Comment by fabricecaruso** [comment]
Still not related to ES. Please close the issue & create a new one in batocera.linux...

**Comment by mistepien** [comment]
But switch in ES is a ES matter.

**Comment by fabricecaruso** [comment]
Don't trust you eyes ;-) It's not because you see it there, that the responsability is here.

Features for system & games are abtract to ES, and it's on purpose. 

Let me explain :

Features are driven by a configuration file ( es_features.yml in batocera.linux repository, es_features.xml once deployed ). 
ES just display the options described in this file & load/writes the result from/to the config file. 
That's all.

Then, when you run a game, options are read & processed by a launcher ( here : configgen/emulatorLauncher which is a project inside batocera.linux repository ).

The advantage of that, is that retrobat (windows equivalent) or emuElec (runs on Amlogic devices) have their own es_features file & the options can be different from batocera.linux in their implementation.

ES does not know the options at all : It just displays & store what's described in the file...

So : NO, it's absolutely NOT related to ES.

Please close the issue & create a new one in batocera.linux...
