### ISSUE TITLE
vulkan graphics backend and shaders

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#635]
In last beta upgrade (31.X) in per system setting there is a new option "Graphics backend" with choice between opengl and vulkan.
Problem is that if you turn on vulkan options then shaders does not work, even if you can still change and select shaders.

**Comment by fabricecaruso** [comment]
Not related to ES... Please close issue & create a new issue in batocera.linux repository

**Comment by mistepien** [comment]
I can not agree with that what you said. ES is not synchronized with limitations of lower layers. If you choose vulkan graphic backend then shader should be automatically set to "none". Otherwise it is confusing.

**Comment by fabricecaruso** [comment]
One more time : _**IT IS NOT RELATED TO ES.**_ 

The problem happens because shaders have different file format with Vulkan, and they have to be added.
But it's on batocera.linux side. Not ES side.

Plus, as I already said many times. ES does not know the game & system options. It just displays them.
And there is not interdependency mecanism between features.

So please close issue & create a new issue in batocera.linux repository

**Comment by Darknior** [comment]
Yes ES is only like a menu @mistepien ... you can't ask it that.
ES show an option and behind Batocera use the option wish bash scripts like configuen.
If you have a bug not visual in ES ONLY, you must ask to Batocera team and not here !!!

**Comment by mistepien** [comment]
But there is no possibility to create a new issue in batocera.linux repository. All you can do is a pull request.

**Comment by Darknior** [comment]
Yes we know, you must go to speak on discord. No issues possible.

**Comment by fabricecaruso** [comment]
Mmmm you're right... I'll talk about it to the team members. I don't have rights on batocera.linux repository

**Comment by mistepien** [comment]
It would be great. Any way thanks for the answer.
