### ISSUE TITLE
Retroachievements on/off then show/hide achievements in UI

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#776]
Hello team,
When the Retroachievement option is disabled the "Retroachievements" system remains active in the systems view, and also the icons in the playlists. I think it would be more intuitive to hide everything related to achievements in UI if the Retroachievements option from the main menu is deactivated.

What do you think about this?

**Comment by Darknior** [comment]
yes good idea

**Comment by fabricecaruso** [comment]
I don't agree :
- The collection is not visible by default. If it's visible it's because the user activated it manually.
- Leaving the collection accessible is also a way to tell the users " hey, guys, when you activate retroachievements & index your games you have a collection that is automatically filled ", so they understand there's a value activating it !
- If it's hidden as a system, it has to be hidden too in the "choose auto collections screen", so nobody will ever now there's such a collection without activating retroachivements.
- We could just "disable the collection" when "switching retroachivements" off, but I don't see any real interest since it would still be visible in the "choose auto collections screen"

**Comment by pajarorrojo** [comment]
I understand Fabrice, the subject of the collection is complex, but right now if you have indexed the games for Retroachievements and later you do not want to use this feature, the trophy icons continue to appear in the list of games, I think this is an information that the user does not need if he decides to deactivate retroachievements and can even be annoying on screen.

**Comment by pajarorrojo** [comment]
As it works today is through indexing, if there is no indexing of achievements, we do not see games in the collection and we do not see games marked in the game lists even if we have achievements activated.

Maybe it's as easy as indexing when we activate Retroachievements / Delete indexing when we deactivate. When we activate, we can ask, "Is it required to scan the games for achievements, do you want to scan now?".

With this method we also let the user know that indexing is required, right now that information is not available either and it can be confusing to activate the achievements and see an empty collection.

**Comment by shantigilbert** [comment]
@pajarorrojo please no, that's a terrible idea, specially for people that have thousands of roms, deleting the indexing data when deactivating it is just wasteful. I think a better approach is to educate the user on how this works, maybe a wiki entry or something, there is enough hand holding as it is and bloating the software, or wasting time indexing / re-indexing just because someone does not want to read how to use it is not the way to go, IMHO

**Comment by pajarorrojo** [comment]
@shantigilbert Yes, it's true, eliminating it by brute force is not the best option, especially in very large lists, maybe just stop calling the indexing of achievements if turned off would be a good measure if this is possible.

Anyway, now it's not intuitive in these two possible scenarios
- Retroachievements ON / no index = No games in achievement collection, no icon in lists.
- Retroachievements OFF / index exists = The info continues in the interface.

**Comment by shantigilbert** [comment]
I might be misunderstanding this, if so I apologize, but the indexing is done once (automatically if its the first time you enable it), and never again, unless you trigger it manually, its not something that is always running in the background, so there is nothing to stop. 

So I think you mean stop showing the trophy if RA is not active, right? 

- RA ON / no index (not sure how that is possible unless you turn off your device mid-scan?) in this case, a manual scan should be triggered by the user. 
- RA OFF / index = In this case turn off the trophy symbol, right? 

A possible solution for scenario 1 would be to trigger a scan only on ROMS that are missing RA info each time they enable RA, but I still don't know how this would impact the RA server.

**Comment by pajarorrojo** [comment]
@shantigilbert It's true, I have tried a fresh installation and when you activate the achievements, it checks credentials, it invites you to register at retroachivements.org if you are not registered and starts an indexing when you have the credentials and activate again the switch. Scenario 1 is not possible

Now I'm not sure, but in my personal installation, I activated the achievements to see the new features of version 30 and the indexing did not start automatically, I had to do it manually, hence my confusion, sorry. I don't know if this has happened to someone else.

**Comment by fabricecaruso** [comment]
I do agree about the "trophy icons" thing.
It's a good idea to disable it when the option is off, excecially in the basic/detailed/video views.

But, I don't agree about the other suggestions : 
- Removing what's been indexed is totally useless & unproductive.
- Hiding / emptying the retroachivements collections is also useless & unproductive to me. If the user does not want to see the collection anymore, he can hide it. & If he does not, he's remembered the feature exists...

**Comment by pajarorrojo** [comment]
Yes @fabricecaruso, maybe the most annoying thing is the issue of trophy icons on the lists. For the rest of the points the user has the option to decide what to do with.

**Comment by fabricecaruso** [comment]
I'm working on the icon things.. I'll commit it soon.
